services:
  wp-db:
    image: mariadb:11
    container_name: wp_site_db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      MYSQL_DATABASE: wp_site
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: TROCAR_SENHA_DB
      MYSQL_ROOT_PASSWORD: TROCAR_SENHA_ROOT_DB
    volumes:
      - wp_site_db_data:/var/lib/mysql
    networks:
      - wp_site_net

  wordpress:
    image: wordpress:6.8-php8.3-apache
    container_name: wp_site_app
    restart: unless-stopped
    depends_on:
      - wp-db
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_NAME: wp_site
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: TROCAR_SENHA_DB
    ports:
      - "127.0.0.1:8085:80"
    volumes:
      - wp_site_data:/var/www/html
    networks:
      - wp_site_net

volumes:
  wp_site_db_data:
  wp_site_data:

networks:
  wp_site_net:
    driver: bridge
